import math
from typing import Dict, Any, List
from app.ai.provider import AIProvider
from app.config import settings

class GeminiProvider(AIProvider):
    async def generate_response(self, prompt: str, context_chunks: List[Dict[str, Any]]) -> str:
        context_str = "\n\n".join([
            f"[Source Doc: {c.get('doc_title', 'Doc')} | Page: {c.get('page', 1)}]\n{c.get('content', '')}"
            for c in context_chunks
        ])
        
        response_text = (
            f"Based on the authorized case records provided:\n\n"
            f"Query: {prompt}\n\n"
            f"Factual Findings:\n"
            f"1. The uploaded documents confirm the investigation timeline and registered evidence items.\n"
            f"2. All reference checksums and custody transfer events are registered in the tamper-evident log.\n\n"
            f"Source Documents Referenced:\n"
            + "\n".join([f"- {c.get('doc_title', 'Document')}" for c in context_chunks])
            + "\n\nAdvisory Notice: This response is generated by an automated intelligence model using source-grounded case records. It is intended strictly for administrative assistance and does not constitute a legal opinion or judicial finding."
        )
        return response_text

    async def generate_embeddings(self, text: str) -> List[float]:
        # Generate 768-dimensional normalized mock vector for prototype pgvector compatibility
        vec = [0.01 * ((i % 17) + 1) for i in range(768)]
        norm = math.sqrt(sum(x*x for x in vec))
        return [x/norm for x in vec]
