from fastapi import APIRouter, Depends
from pydantic import BaseModel
from typing import List, Optional
from app.core.security import get_current_user, AuthenticatedUser
from app.ai.factory import get_ai_provider, get_active_provider_name, set_active_provider_name
from app.services.audit_service import record_audit_event

router = APIRouter(prefix="/ai", tags=["ai"])

class ChatQueryPayload(BaseModel):
    case_id: str
    query: str

class AIProviderTogglePayload(BaseModel):
    provider: str  # 'gemini' or 'ollama'

class EntityExtractPayload(BaseModel):
    document_title: str
    content_text: str

# Dataset of Cross-Jurisdiction Matches across police departments
MOCK_CROSS_CASE_ENTITIES = [
    {
        "id": "ent-101",
        "entity_type": "suspect",
        "entity_value": "Vikram @ Vicky Malhotra",
        "primary_case_id": "NV-2026-001",
        "matched_case_id": "NV-2026-002",
        "matched_jurisdiction": "Mumbai Sessions Court (Cyber Division)",
        "matched_fir": "FIR 089/2026 - Financial Fraud",
        "confidence_score": 0.96,
        "notes": "Same suspect alias linked to unauthorized SIM swapping gang"
    },
    {
        "id": "ent-102",
        "entity_type": "bank_account",
        "entity_value": "A/C 91802004819201 (HDFC Bank)",
        "primary_case_id": "NV-2026-001",
        "matched_case_id": "NV-2026-007",
        "matched_jurisdiction": "Bengaluru Police Central Crime Branch",
        "matched_fir": "FIR 0412/2026 - Ransomware Extortion",
        "confidence_score": 0.99,
        "notes": "Mule account used to route illicit fund transfers"
    },
    {
        "id": "ent-103",
        "entity_type": "vehicle",
        "entity_value": "DL 01 AB 8842 (White SUV)",
        "primary_case_id": "NV-2026-001",
        "matched_case_id": "NV-2026-003",
        "matched_jurisdiction": "Noida Sector 62 Police Station",
        "matched_fir": "FIR 0104/2026 - Electronic Theft",
        "confidence_score": 0.91,
        "notes": "CCTV vehicle match logged during evidence seizure window"
    }
]

@router.get("/provider")
async def get_current_ai_provider():
    return {
        "active_provider": get_active_provider_name(),
        "available_providers": ["gemini", "ollama"]
    }

@router.post("/provider")
async def toggle_ai_provider(payload: AIProviderTogglePayload, current_user: AuthenticatedUser = Depends(get_current_user)):
    new_provider = set_active_provider_name(payload.provider)
    record_audit_event(
        actor_id=current_user.id,
        action="AI_PROVIDER_TOGGLED",
        resource_type="system",
        resource_id=new_provider,
        result="success",
        reason=f"Switched AI provider engine to {new_provider}"
    )
    return {
        "active_provider": new_provider,
        "message": f"AI Engine switched to {new_provider.upper()}"
    }

@router.post("/chat")
async def chat_with_case_context(payload: ChatQueryPayload, current_user: AuthenticatedUser = Depends(get_current_user)):
    provider = get_ai_provider()
    
    context_chunks = [
        {
            "doc_title": "Primary FIR Copy — Cyber Fraud",
            "page": 1,
            "content": "FIR 0482 filed regarding unauthorized electronic funds transfer of INR 4,50,000."
        },
        {
            "doc_title": "Forensic Seizure Report",
            "page": 2,
            "content": "Digital evidence drive EVD-2026-DEL-001 retrieved with SHA-256 reference hash 4b227777d4dd..."
        }
    ]

    answer = await provider.generate_response(payload.query, context_chunks)

    record_audit_event(
        actor_id=current_user.id,
        action="AI_RAG_QUERY_EXECUTED",
        resource_type="case",
        resource_id=payload.case_id,
        result="success",
        reason=f"Query via {get_active_provider_name()}: {payload.query[:30]}..."
    )

    return {
        "answer": answer,
        "sources": context_chunks,
        "active_provider": get_active_provider_name(),
        "disclaimer": "Advisory Notice: This response is generated by an automated intelligence model using source-grounded case records. It is intended strictly for administrative assistance and does not constitute a legal opinion or judicial finding."
    }

@router.get("/cross-case-matches")
async def get_cross_case_matches(case_id: Optional[str] = None, current_user: AuthenticatedUser = Depends(get_current_user)):
    if case_id:
        return [e for e in MOCK_CROSS_CASE_ENTITIES if e["primary_case_id"] == case_id or e["matched_case_id"] == case_id]
    return MOCK_CROSS_CASE_ENTITIES

@router.post("/extract-entities")
async def extract_and_match_entities(payload: EntityExtractPayload, current_user: AuthenticatedUser = Depends(get_current_user)):
    record_audit_event(
        actor_id=current_user.id,
        action="AI_ENTITY_EXTRACTION_PERFORMED",
        resource_type="document",
        resource_id=payload.document_title,
        result="success"
    )
    return {
        "extracted_entities": [
            {"type": "suspect", "value": "Vikram @ Vicky Malhotra", "confidence": 0.96},
            {"type": "bank_account", "value": "A/C 91802004819201", "confidence": 0.99},
            {"type": "vehicle", "value": "DL 01 AB 8842", "confidence": 0.91}
        ],
        "cross_jurisdiction_matches": MOCK_CROSS_CASE_ENTITIES
    }
